### PR TITLE
Add new question, catagory and added medium difficulty.

### PR DESCRIPTION
**Pull request by ghost**
``{
        "question": {
            "options": [
                "by debouncing the function",
                "using a timeout",
                "implementing a custom hook with a useMemo hook",
                "using a promise"
            ],
            "question": {
                "text": "How can you prevent a function from being called multiple times in a short period of time in React?",
                "codeSnippet": null
            },
            "correctAnswer": "by debouncing the function"
        },
        "category": "React",
        "difficulty": "easy",
        "your_name": "SlowMoschen",
        "your_github_url": "github.com/SlowMoschen"
    },
    {
        "question": {
            "options": [
                "Bubble sort",
                "Quick Sort",
                "Merge Sort",
                "Fibonacci Sequence"
            ],
            "question": {
                "text": "What algorithm is described in the following? 'Checks a list of elements, comparing each adjacent elements from lowest and highest, and swapping them if needed.' ",
                "codeSnippet": null
            },
            "correctAnswer": "Bubble sort"
        },
        "category": "Algorithms",
        "difficulty": "medium",
        "your_name": "Brandonbr1",
        "your_github_url": "github.com/Brandonbr1"
    },
JSON``

### CODE REVIEW

**Comment by llo7d** [comment]
@brandonmohammedfromsgss
This is great! Well done.
I really like the idea of creating a new category called "Algorithms" but could you include a code snippet with the questions? Also, maybe add a few more algorithm questions?.

Remove the adjustments to popup.jsx, and commit again with making thanges only inside questions.json

**Review by lloyd-december — CHANGES_REQUESTED** [review]
This is great! Well done.
I really like the idea of creating a new category called "Algorithms" but could you include a code snippet with the questions? Also, maybe add a few more algorithm questions?.

Remove the adjustments to popup.jsx, and commit again with making thanges only inside questions.json

**Comment by ghost** [comment]
> This is great! Well done. I really like the idea of creating a new category called "Algorithms" but could you include a code snippet with the questions? Also, maybe add a few more algorithm questions?.
> 
> Remove the adjustments to popup.jsx, and commit again with making thanges only inside questions.json

I've undone the changes for popup.jsx.

As for adding more questions, I may add more. I will see.

**Review by lloyd-december — CHANGES_REQUESTED** [review]
This is good, 
but include a code snippet, I generated this with AI, im not sure if its right but you get the idea.


`   "question": {
      "text": "What algorithm is described in the following? 'Bruteforcing or searching data to find the best potential candidate for a solution; incrementally building the candidate if deemed fit and if not then dumping it.'",
      "codeSnippet": "def solve_problem(candidate):\n    if is_solution(candidate):\n        return candidate\n    for next_candidate in generate_candidates(candidate):\n        if is_valid(next_candidate):\n            result = solve_problem(next_candidate)\n            if result is not None:\n                return result\n    return None\n\n# Example usage:\ninitial_candidate = []  # starting with an empty candidate\nsolution = solve_problem(initial_candidate)\nprint(\"Solution found:\", solution)"
    },
 `

**Pull request closed without merging**
