### PR TITLE
Add 4 questions on each topic

### PR DESCRIPTION
**Pull request by yatochka-dev**

### CODE REVIEW

**Review by lloyd-december — CHANGES_REQUESTED** [review]
Sorry,
I provided a old version of .json exmaple it should look like this:

```json
{
    "question": {
        "options": [
            "<App />",
            "App()",
            "new App()",
            "App.render()"
        ],
        "question": {
            "text": "How do you render the App component in a React application?",
            "codeSnippet": "const App = () => <div>Hello, world!</div>;"
        },
        "correctAnswer": "<App />"
    },
    "category": "react",
    "difficulty": "easy",
    "your_name": "looyd",
    "your_github_url": "github.com/llo7d"
},
```

**Comment by yatochka-dev** [comment]
Np, I'll change it when I get to my PC.

**Comment by yatochka-dev** [comment]
I added changes according to the new question version.

**Review by lloyd-december — APPROVED** [review]

**Comment by lloyd-december** [comment]
@yatochka-dev Why did your remove your github and your name? Add it back in

**Review by lloyd-december — CHANGES_REQUESTED** [review]
Add your name & github back in

**Comment by yatochka-dev** [comment]
Oh, I Ctrl c Ctrl v the template, 1s.

**Pull request merged**
